### ISSUE TITLE
Stock Kardex Report Not Compatible with Latest version. 

### ISSUE THREAD

**Issue by pubalansivasangkar** [OCA/stock-logistics-reporting#258]
Hi,

I found this report not compatible with the newer version of Odoo. Please help to update the new version. so everyone can use it for the newer version.  i try to update on v14 odoo it's becoming failed in odoo.sh. please help me to check. 

Thanks Regards
Pubalan

**Comment by pubalansivasangkar** [comment]
i got error like this

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/odoo/models.py", line 4245, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/odoo/models.py", line 4161, in _load_records_create
    return self.create(values)
  File "<decorator-gen-163>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 329, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/odoo/api.py", line 329, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/enterprise/web_studio/models/studio_mixin.py", line 19, in create
    res = super(StudioMixin, self).create(vals)
  File "<decorator-gen-48>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 347, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 259, in create
    return super(IrActionsActWindow, self).create(vals_list)
  File "<decorator-gen-46>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 47, in create
    res = super(IrActions, self).create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/models.py", line 3842, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
ValueError: Invalid field 'view_type' on model 'ir.actions.act_window'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1392, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1380, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 478, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 596, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 459, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /home/odoo/src/user/stock_kardex_report/wizard/stock_kardex_report_wizard_view.xml:23, near
<record id="action_stock_kardex_report" model="ir.actions.act_window">
        <field name="name">Stock Kardex Report</field>
        <field name="res_model">stock.kardex.report.wiz</field>
        <field name="view_type">form</field>
        <field name="view_mode">form</field>
        <field name="view_id" ref="view_stock_kardex_report"/>
        <field name="target">new</field>
    </record>

**Comment by rousseldenis** [comment]
> Hi,
> 
> I found this report not compatible with the newer version of Odoo. Please help to update the new version. so everyone can use it for the newer version. i try to update on v14 odoo it's becoming failed in odoo.sh. please help me to check.
> 
> Thanks Regards Pubalan

@pubalansivasangkar It seems module for v14 is not yet available. How did you install it ?

**Comment by pubalansivasangkar** [comment]
HI @rousseldenis. i just upload to GitHub & run on odoo.sh.

**Comment by rousseldenis** [comment]
> HI @rousseldenis. i just upload to GitHub & run on odoo.sh.

Could you please confirm that you have an instance on odoo.sh (and Saas) and try to upgrade from a previous version to  14.0 ?

As said, module is not in v14. As I don't know Odoo.sh, you maybe need someone to upgrade it for you
