### ISSUE TITLE
[12.0] Bug when changing filter or grouping

### ISSUE THREAD

**Issue by BT-panken** [OCA/stock-logistics-reporting#98]
Hello,

Selecting a groupby or a filter in the report lead to following error:

```
Uncaught TypeError: currentController.widget.reload is not a function
http://localhost:8069/web/content/519-141d138/web.assets_backend.js:518
Traceback:
TypeError: currentController.widget.reload is not a function
    at Class._onSearch (http://localhost:8069/web/content/519-141d138/web.assets_backend.js:518:1023)
    at Class.<anonymous> (http://localhost:8069/web/content/518-39c8cb3/web.assets_common.js:3643:11)
    at Class.trigger (http://localhost:8069/web/content/518-39c8cb3/web.assets_common.js:3641:180)
    at Class._trigger_up (http://localhost:8069/web/content/518-39c8cb3/web.assets_common.js:3647:378)
    at Class._trigger_up (http://localhost:8069/web/content/518-39c8cb3/web.assets_common.js:3647:462)
    at Class.trigger_up (http://localhost:8069/web/content/518-39c8cb3/web.assets_common.js:3647:280)
    at Class.do_search (http://localhost:8069/web/content/519-141d138/web.assets_backend.js:904:42)
    at child.<anonymous> (http://localhost:8069/web/content/518-39c8cb3/web.assets_common.js:3643:11)
    at triggerEvents (http://localhost:8069/web/content/519-141d138/web.assets_backend.js:40:242)
    at child.trigger (http://localhost:8069/web/content/519-141d138/web.assets_backend.js:35:223)
```

**Test environnement**

Odoo : 32e1effa32e
Enteprise : 5eb519ddbd
stock-logistics-reporting : bebf471
Demo data

How to reproduce:
1.1) Inventory/Reporting/Inventory Valuation --> "View Report" in the popup 
1.2) than Group by --> Warehouse

Thanks in advance for your support.

**Comment by pedrobaeza** [comment]
Which module? Detailed steps to reproduce the problem?

**Comment by BT-panken** [comment]
Information added.

**Comment by rousseldenis** [comment]
Reproduced on runbot. But I think filters are not to be used in that case. @ps-tubtim Could you confirm ?

**Comment by BT-jstein** [comment]
Hallo @pedrobaeza @ps-tubtim @rousseldenis 

are there any news?

**Comment by ps-tubtim** [comment]
@rousseldenis I agree with you. I will fix it.
@All Could anyone suggest me a solution for this problem?

**Comment by BT-panken** [comment]
Only dirty option I see would be custom JS loaded with the view which would hide the elements.

**Comment by BT-aestebanez** [comment]
@ps-tubtim 
In my opinion there are three options:
1. To hide the div.o_control_panel: This would prevent people of trying to filter, group, etc.
2. To adapt the whole layout to have something similar to what Odoo implements for Accounting -> Reports
3. To create a report model like Sales -> Reporting.

Currently, Odoo thinks you are using a common view but you are actually inheriting from web.Widget and some methods such as `reload()` are not declared.
In fact, and as far as I can see in the code, what is shown is HTML code without any possibility of handling it.

Thanks in advance for your work
Alvaro

**Comment by DEVHSCO** [comment]
Some help to solve this problem?
